---
resources:
- name: source
  type: git
  source:
    uri: ((source_uri))
    private_key: ((source_private_key))
- name: plugin-release-draft
  type: github-release
  source:
    owner: ((plugin_owner))
    repository: ((plugin_repo))
    access_token: ((source_access_token))
    pre_release: true
- name: plugin-release
  type: github-release
  source:
    owner: ((plugin_owner))
    repository: ((plugin_repo))
    access_token: ((source_access_token))
- name: version
  type: semver
  source:
    driver: s3
    bucket: ((source_semver_bucket))
    access_key_id: ((source_access_key_id))
    secret_access_key: ((source_secret_access_key))
    key: ((plugin_repo))-version
    initial_version: 0.0.1

jobs:
- name: test-and-build
  plan:
  - in_parallel: 
    - get: source
      trigger: true
    - get: version
      params:  
        pre: build
  - task: test-and-build
    file: source/ci/tasks/test-and-build.yml
  - in_parallel:
    - put: version
      params:
        file: version/version
    - put: plugin-release-draft
      params:
        name: version/version
        tag: version/version
        tag_prefix: v

- name: publish-release
  plan:
  - in_parallel:
    - get: source
      passed: [test-and-build]
    - get: version
  - task: test-and-build
    file: source/ci/tasks/test-and-build.yml
  - put: version
    params: {bump: final}
  - put: plugin-release
    params:
      name: version/version
      tag: version/version
      tag_prefix: v 
      globs: 
      - "binaries/services-auditor-plugin-*"
  - put: version
    params: {bump: patch}

- name: bump-minor
  plan:
  - put: version
    params: {bump: minor}

- name: bump-major
  plan:
  - put: version
    params: {bump: major}
